[WIP] feat: Create RegisterInput
teamtopping/FrontEnd pull request #12
Opened 2021-12-10 04:24 UTC by WJ951009

2021-12-10 15:21 UTC, WJ951009 commented
- focus 이벤트를 molecules에 구현해 두었는데, 이에 대한 의견이 궁금합니다.
> (회원가입 페이지에서 발생하는 focus 이벤트는 value에 상관없이 input의 아래 테두리 색상의 변경입니다)

<br>

- 유효성 검사 후 발생하는 이벤트(아이콘과 스타일 변경)는 template 혹은 organism 단위에서 진행하려 합니다. 구조에 관련해 생각이 다르시다면 피드백 부탁 드립니다. (+ value 포함)

2021-12-11 06:43 UTC, JinleeJeong requested changes

2021-12-11 06:43 UTC, JinleeJeong commented on src/components/molecules/RegisterInput.tsx
> +export interface RegisterInputProps extends PublicTextInputProps {
PublicTextInputProps를 받는건 너무 의존성이 많아져서 나중에 찾기 복잡할 것 같아요!

필요한건 props로 추가해서 하는건 어때요?

2021-12-11 06:43 UTC, JinleeJeong commented on src/components/molecules/RegisterInput.tsx
> +            {props.value}
props.value는 PublicTextInput props에 value를 이용해서 넣으면 되지 않을까요!?

2021-12-11 06:43 UTC, JinleeJeong commented on src/components/molecules/RegisterInput.tsx
> +            img={props.value ? IMAGES.delete : null}>
PublicTextInput은 imageSourcePropsType이거나 undefined 입니다! 

null 타입은 정의 되지 않았어요!

2021-12-11 06:43 UTC, JinleeJeong commented on src/components/molecules/RegisterInput.tsx
> +  returnZone: {
Zone이라는 네임은 잘 사용되지 않아요

Container가 더 어울리지 않을까 싶습니다!

2021-12-11 06:43 UTC, JinleeJeong commented on src/components/molecules/RegisterInput.stories.tsx
> +// import {action} from '@storybook/addon-actions';
사용되지 않는 코드는 임시적으로 보아야 하지 않는다면 지우는게 좋아요!

2021-12-11 06:44 UTC, JinleeJeong commented
> >

이 부분에 대해서는 page나 template를 만들어보면서 수정할 필요가 있을 것 같아요! 직접 개발해보면 다를 수 있어요!

우선 지금 봣을때는 괜찮아 보입니다!

2021-12-11 06:44 UTC, JinleeJeong commented
> * focus 이벤트를 molecules에 구현해 두었는데, 이에 대한 의견이 궁금합니다.
> 
> > (회원가입 페이지에서 발생하는 focus 이벤트는 value에 상관없이 input의 아래 테두리 색상의 변경입니다)
> 
> 
> * 유효성 검사 후 발생하는 이벤트(아이콘과 스타일 변경)는 template 혹은 organism 단위에서 진행하려 합니다. 구조에 관련해 생각이 다르시다면 피드백 부탁 드립니다. (+ value 포함)

이 부분에 대해서는 page나 template를 만들어보면서 수정할 필요가 있을 것 같아요! 직접 개발해보면 다를 수 있어요!

우선 지금 봣을때는 괜찮아 보입니다!

2021-12-11 22:53 UTC, kyuhyunhan commented on src/components/molecules/RegisterInput.tsx
> +      <View style={styles.header}>
header라는 게 html에서 통상적으로 의미하는게 있는 태그기 때문에, 저같은 경우에는 그 의미를 살려 마크업을 하고, 리액트에서 클래스네임을 붙일 때도 혼동되지 않게 고려하는 편입니다.
보통 input이랑 붙는건 label이라는 용어가 붙는데 이 부분을 label로 변경하는건 어떠실까요?!

2021-12-11 22:53 UTC, kyuhyunhan commented on src/components/molecules/RegisterInput.tsx
> +        <Text style={styles.title}>{props.title}</Text>
props로 받는 부분도 title보다는 label이 더 정확한 표현이지 않을까 싶습니다!

2021-12-11 22:54 UTC, kyuhyunhan commented
> > * focus 이벤트를 molecules에 구현해 두었는데, 이에 대한 의견이 궁금합니다.
> > 
> > > (회원가입 페이지에서 발생하는 focus 이벤트는 value에 상관없이 input의 아래 테두리 색상의 변경입니다)
> > 
> > 
> > 
> > * 유효성 검사 후 발생하는 이벤트(아이콘과 스타일 변경)는 template 혹은 organism 단위에서 진행하려 합니다. 구조에 관련해 생각이 다르시다면 피드백 부탁 드립니다. (+ value 포함)
> 
> 이 부분에 대해서는 page나 template를 만들어보면서 수정할 필요가 있을 것 같아요! 직접 개발해보면 다를 수 있어요!
> 
> 우선 지금 봣을때는 괜찮아 보입니다!

저도 지금은 괜찮은 것 같습니다 bb

2021-12-11 23:03 UTC, kyuhyunhan commented on src/components/molecules/RegisterInput.stories.tsx
> +        returnMsg={STRING.enableNick}
@WJ951009 @JinleeJeong 이 부분에 return -> error 는 어떠신가요? 저는 항상 form에서 이 부분을 그렇게 써왔는데, return도 의미상 잘못된 것 같지는 않아서.. 두 분 생각은 어떠신가요?

2021-12-12 04:45 UTC, WJ951009 commented on src/components/molecules/RegisterInput.stories.tsx
> +        returnMsg={STRING.enableNick}
처음에는 PublicInput에서 사용하려고 return이라는 네이밍을 했는데, RegisterInput로 옮긴 후에는 error나 warning 맞는 표현인것 같습니다..! 저는 수정하는게 맞다고 생각합니다

2021-12-12 04:48 UTC, WJ951009 commented on src/components/molecules/RegisterInput.tsx
> +            img={props.value ? IMAGES.delete : null}>
와우..!! 전혀 인지하고 있지 못 했습니다. 감사해요

2021-12-13 15:16 UTC, kyuhyunhan approved these changes

2021-12-14 01:29 UTC, JinleeJeong requested changes
Can you fix the comflict?

2021-12-14 01:47 UTC, WJ951009 commented
> Can you fix the conflict?

now, i'm done 😄

2021-12-14 01:48 UTC, JinleeJeong approved these changes

2021-12-14 01:48 UTC, merged