[WIP]feat: create RegisterTemplate
teamtopping/FrontEnd pull request #18
Opened 2021-12-14 05:52 UTC by WJ951009

2021-12-16 04:22 UTC, WJ951009 commented
템플릿을 만들면서 상위 컴포넌트에서 불러서 써보니, props를 재정의 해야 할 일이 많았고 page까지 미리 만들어서 체크 하면서 정리했습니다.
전부 원하는대로 동작하게 만들기는했는데, 정리한다고 정리했는데도 너무 난잡해서 리뷰 요청드립니다.

page에서 닉네임,이메일 중복체크에 관련하여 서버에서 받을 데이터를 isCertified라는 props로 내려줄 생각이고,
이외에는 pages에서 템플릿에 필요한 각각의 props를 State로 처리할 생각입니다.

2021-12-16 04:25 UTC, WJ951009 commented
@kyuhyunhan 제가 MainButton의 disabled를 사용하면서 스타일 관련해서 처리를 못해서 PublicButton을 이용했습니다. 관련해서 도움주시면 감사하겠습니다 😢 

추가로 디자인안에서 배경색이 흰색으로 같을때 하이라이트 된 흰색 테두리를 어떻게 표현해야 할지 여쭤보고 싶습니다.

2021-12-16 04:45 UTC, JinleeJeong requested changes

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/atoms/PublicTextInput.tsx
> +interface PublicTextInputProps extends TextInputProps {
이미 PublicTextInput이라는 파일에서 props이라서, 다른데에서 사용하지 않는다면, 그냥 props로 만들어서 밑에 나눠줘도 될 것 같아요!

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/molecules/MainButton.stories.tsx
> +      <MainButton title={'다음'} disabled={true} onPress={action('onPress')} />
<MainButton title={'다음'} disabled onPress={action('onPress')} />

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/molecules/MainButton.tsx
> +    width: '100%',
100%와 98%의 이유를 적어주면 좋을 것 같아요!

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/molecules/RegisterInput.stories.tsx
>          label={'비밀번호'}
label들도, 통일되서 STRING 파일을 사용하는건 어떤가요 ?

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/pages/RegisterPage.tsx
> +  const [email, setEmail] = useState('');
email pwd checkpwd nick 이렇게 4개를 사용하는데, 인터페이스로 빼고, 객체 하나를 사용한 state는 어떤가요?
valid도요!

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/pages/RegisterPage.tsx
> +        onChangePwd={p => setPwd(p)}
element는 p, cP, N이렇게 잘 사용하지 않아요
onChange에서 오는 값은 element라서 element나 e 등을 사용합니다!

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/templates/RegisterTemplate.tsx
> +  checkPwdErrMsg?: string;
몇개 msg는 page에서 props으로 안넘겨주는데, 이건 어떻게 되나요 ?

2021-12-16 04:45 UTC, JinleeJeong commented on src/components/templates/RegisterTemplate.tsx
> +        <Text style={styles.title}>
Text내에 Text로 감싸지 않아요, View로 감싸야 해요

2021-12-16 14:53 UTC, kyuhyunhan commented
> @kyuhyunhan 제가 MainButton의 disabled를 사용하면서 스타일 관련해서 처리를 못해서 PublicButton을 이용했습니다. 관련해서 도움주시면 감사하겠습니다 😢
> 
> 추가로 디자인안에서 배경색이 흰색으로 같을때 하이라이트 된 흰색 테두리를 어떻게 표현해야 할지 여쭤보고 싶습니다.

저도 조금 고민이 되네요. MainButton이 다른 버튼들이랑 너무 다르게 생겼다보니 불가피하게 molecules로 만든거여서, 
저도 disabled된 button은 (원진님이 하신것처럼) 분기를 쳐서 PublicButton에 disabled를 내리는 방법으로 구현을 생각하긴 했었어요.

좀더 생각을 해봤는데,
1. PublicButton를 개선해서, MainButton 스타일을 소화(?)할 수 있게 하는 방법이 있겠는데, 저도 이건 방법을 모르겠더라구요 ㅠ.ㅠ

2. Mainbutton 컴포넌트 내부에서 props의 disabled  값에 따라 PublicButton을 불러와서 disabled 형태로 구현하는 방법이 하나 떠오르긴합니다.
```
const MainButton = ({disabled, ...props}: Props) => {
  if(disabled) {
    return (
      <PublicButton 
        buttonStyle={{
          borderWidth: 1,
          borderColor: colors.GRAY05,
          width: maxScale(320),
        }}
        textStyle={{
          color: colors.GRAY02,
        }}
        disabled 
        {...props}
      />
    )
  }
  return (
    <View style={styles.wrapper}>
      <PublicButton
        buttonStyle={styles.button}
        textStyle={styles.buttonText}
        {...props}
      />
    </View>
  );
};
```
*대충 이런식으로요?*

이런식으로 해서 이제 화면에 구현되는 버튼컴포넌트의 최소단위는 molecules 레벨의 XXButton으로 사용하고, PublicButton은 그 버튼들의 내부에서만 사용되도록 하는 거예요. 
썩 깔끔한 방법은 아닌것 같지만 disabled를 props로 사용할 수 있는 button 컴포넌트의 의미를 지키기 위해서 이렇게도 우회할 수 있을 것 같습니다.

2021-12-16 14:59 UTC, kyuhyunhan approved these changes, later dismissed

2021-12-17 09:03 UTC, WJ951009 commented
> 

넵 감사합니다. MainButton의 disable을 이용해서 반영했습니다 !

흰색 테두리 하이라이트는 피그마에서 배경색과 테두리 색이 같은 색으로 나오는데 테두리가 강조되어 있길래.. 칼라픽으로 찍어보니까 배경색이 흰색이 아니네요..!<br>

<img width="882" alt="스크린샷 2021-12-17 18 01 18" src="https://user-images.githubusercontent.com/82315118/146517976-19f241e8-e923-4031-bd23-f896d507ab8e.png">

2021-12-17 16:46 UTC, kyuhyunhan commented on src/components/molecules/MainButton.tsx
> +    width: '100%',
MainButton 가로 크기가 다른 버튼들보다 더 커서, 다시 maxScale(320)으로 바꿔보니 괜찮아지더라구요. 이 부분을 어떻게 100%로 입력하게 되신건지 궁금합니다!

2021-12-19 05:49 UTC, JinleeJeong approved these changes
수고하셨어요! 적당한건 PR 반영하고, 넘어가요!!

2021-12-19 05:49 UTC, JinleeJeong commented on src/components/atoms/PublicTextInput.tsx
> +interface PublicTextInputProps extends TextInputProps {
이 부분은 리뷰가 반영된건가요!?

2021-12-19 05:49 UTC, JinleeJeong commented on src/components/molecules/MainButton.tsx
> +// };
꼭 필요하지 않은 부분은 주석처리 안하는게 좋아보여요!

2021-12-19 05:49 UTC, JinleeJeong commented on src/components/templates/RegisterTemplate.tsx
> +import {ValueObj, ValidObj} from '../pages/RegisterPage';
이 네이밍은 위험할 수 있어요! ValueObj라는 것은 다른 곳에서도 사용할 수 있어서, 네이밍이 분리 가능하면 좋을 것 같아요 :)

2021-12-19 14:00 UTC, kyuhyunhan approved these changes

2021-12-21 03:51 UTC, merged