[WIP]feat: Craete PublicInput
teamtopping/FrontEnd pull request #9
Opened 2021-12-01 09:08 UTC by WJ951009

2021-12-02 11:03 UTC, WJ951009 commented
I'll add function, Delete values when press DELETE image

2021-12-05 07:26 UTC, kyuhyunhan commented on src/constants/ko.ts
>  export const STRING = {
constants/images.ts 에서는 PascalCase로 프로프티 값들을 설정해주셨는데, 여기는 CamelCase랑 PascalCase가 같이 쓰였네요! 케이스 스타일을 통일해보는게 어떠신지...

2021-12-05 07:27 UTC, kyuhyunhan commented on src/components/molecules/RegisterInput.tsx
> +import PublicInput from '../atoms/PublicTextInput';
export 하는 컴포넌트명이랑  import는 혹시 일부러 다르게 하신걸까요?

2021-12-07 07:49 UTC, JinleeJeong requested changes

2021-12-07 07:49 UTC, JinleeJeong commented on src/constants/ko.ts
> +  checkPass: '비밀번호 다시 한번 입력해주세요',
Pass라고 잘 안쓰고, Pwd라고 많이 사용합니다! 어떻게 생각하나요 ? ?

2021-12-07 07:49 UTC, JinleeJeong commented on src/components/atoms/PublicTextInput.stories.tsx
> +        type={'Default'}
default라고 생각하는데 `Default`라는게 맞나요!? 타입 명시가 잘 안되어 있어요!

TextInputProps에서 default말고 또 들어갈 수 있는게 뭔가요 ? type: string으로 되어 있어서, 어떻게 하면 좋을지 코맨트 적으면 좋을 것 같아요!

2021-12-07 08:52 UTC, JinleeJeong approved these changes
LGTM :) 좋습니다!

2021-12-08 05:58 UTC, JinleeJeong requested changes
Can you check what I mentioned yesterday?

2021-12-08 06:42 UTC, WJ951009 commented
> Can you check what I mentioned yesterday?

Currently, working on it. It'll be done by the day after tomorrow.

2021-12-09 08:00 UTC, JinleeJeong approved these changes
LGTM :) 고생하셨씁니다

2021-12-09 08:00 UTC, JinleeJeong commented on src/components/atoms/PublicTextInput.tsx
>        </View>
```
<View style={styles.inputImg}>
        <TouchableOpacity onPress={() => setValue('')} activeOpacity={0.6}>
          <Image source={value ? props.image : null} />
        </TouchableOpacity>
 </View>
```

2021-12-09 14:39 UTC, kyuhyunhan reviewed
확인했습니다~! 고생하셨습니다:)

2021-12-09 14:40 UTC, kyuhyunhan approved these changes

2021-12-09 23:57 UTC, merged